name: 构建Windows EXE
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: 安装打包依赖
        run: pip install pyinstaller -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: 执行打包脚本
        run: .\build.bat
      - name: 上传生成的EXE
        uses: actions/upload-artifact@v4
        with:
          name: 打包好的程序
          path: dist/*.exe
